// [Task E18] The first-run Welcome note. A brand-new install has no notes, so the
// open-latest-note boot flow lands on a blank editor. app.js creates ONE ordinary note
// from this content on first run so the landing always shows something — and doubles as
// a live demo of the Markdown/code/math renderer, a quick editor guide, and a
// pointer to Ask Owl.
//
// This module is the SINGLE source for the note's id: app.js creates the note with it,
// (a fixed id so the first-run logic can recognize its own note).
export const WELCOME_NOTE_ID = 'welcome-owl-note';
export const WELCOME_NOTE_TITLE = 'Welcome to OWL-Note 🦉';

// The note body — a scannable first-run guide grounded in the features available in the
// current UI. Kept as joined lines rather than a template literal so fenced code, inline
// math, and literal shortcut text stay easy to edit.
export const WELCOME_NOTE_BODY = [
  '# Welcome to OWL-Note 🦉',
  '',
  '**Markdown notes — synced across your devices.**',
  '',
  'OWL-Note is a free, local-first Markdown notebook inside your browser extension. Notes within browser bookmark sync limits automatically sync through your Chrome or Edge account when bookmark sync is enabled. No separate OWL-Note account or subscription is required.',
  '',
  'This is your first note, and it is yours to keep, edit, or delete. It is an ordinary note like any you create, so feel free to make it your own.',
  '',
  '## Start writing',
  '',
  '- Changes save automatically, and the Markdown preview updates as you type.',
  '- Use the **Text** toolbar for headings, lists, **bold**, colors, highlighting, links, alignment, and tables.',
  '- Use **Code**, **Image**, **Draw**, or **File** to insert richer content.',
  '- Use the note search control to find text in this note, or the main search box to search every note.',
  '',
  'Select some text, then use the row above the editor to change its case or font color, highlight it, or align the current line left, center, or right.',
  '',
  'Open **Table ▾** and drag across the grid to choose the table size. While typing in a table, press **Tab** to move between cells and **Alt+Enter** to wrap onto a new line inside the same cell.',
  '',
  '## Code and math, rendered',
  '',
  'Fenced code keeps its formatting:',
  '',
  '```python',
  'def greet(name):',
  '    return f"Hello, {name}!"',
  '```',
  '',
  "And inline math works too, so Euler's identity reads as $e^{i\\pi} + 1 = 0$.",
  '',
  '## ✨ Save web content and AI conversations',
  '',
  'Right-click a selection on a page and choose **Save selection to OWL-Note** to turn it into editable Markdown.',
  '',
  'To save an entire supported AI conversation, right-click the page and choose **Rebuild LLM chat to OWL-Note**. ChatGPT, Claude, Gemini, and similar conversation pages are converted into editable Markdown—not screenshots—with:',
  '',
  '- User and assistant messages',
  '- Headings, paragraphs, lists, and links',
  '- Tables',
  '- Fenced code blocks with syntax highlighting',
  '- KaTeX math',
  '- Supported images as attachments',
  '- The original source URL',
  '',
  'Conversion happens locally inside the extension. No API key or cloud conversion service is required.',
  '',
  '## 📸 Capture an entire page as one long image',
  '',
  'Right-click the page and choose **Capture entire page to OWL-Note**. OWL-Note scrolls and stitches the page, including content below the fold, into one long image.',
  '',
  'This is useful for long articles, technical documentation, assignments and feedback, receipts and confirmations, dashboards, reports, and complex page layouts. Capture and image stitching happen locally.',
  '',
  '## 🎨 Draw and annotate inside your notes',
  '',
  'Click **Draw** to open the built-in sketchpad.',
  '',
  '- Use the pen, highlighter, eraser, or text tool.',
  '- Add lines, arrows, rectangles, rounded rectangles, ellipses, triangles, diamonds, polygons, and stars.',
  '- Choose stroke and fill colors, stroke sizes, text styles, and text backgrounds.',
  '- Hold **Shift** for straight strokes, snapped lines, squares, circles, even shapes, proportional resizing, and snapped rotation.',
  '- Add or paste photos, then select, move, resize, rotate, reorder, or delete objects.',
  '- Undo and redo your changes.',
  '- Save the drawing directly into the note as a PNG attachment.',
  '',
  '## 🎙️ Live transcription',
  '',
  'Right-click a supported playing tab and choose **Live Transcription save to OWL-Note**. Chrome’s native on-device speech recognition turns the tab’s speech into an editable Markdown note.',
  '',
  '- Live captions appear in a draggable overlay while the video continues playing.',
  '- Captions are organized into readable paragraphs with source URL, date, duration, and periodic timestamps.',
  '- Save or discard from the overlay; if the captured tab closes, the transcript is saved automatically.',
  '- The saved transcript opens immediately in OWL-Note.',
  '- Audio is never uploaded or stored.',
  '',
  'Chrome 139 or newer and a supported local speech language are required. Chrome may ask for confirmation before downloading the selected language resource.',
  '',
  '## 🔗 Share and export an individual note',
  '',
  'Open the note’s **Share** menu to:',
  '',
  '- Create a PDF locally and send it through the system share menu.',
  '- Download the PDF when system sharing is unavailable.',
  '- Export an editable `.owl-note` package with supported attachments.',
  '- Optionally create a public, read-only PDF link in your Google Drive.',
  '',
  'Creating a public Drive link always requires confirmation. The shared PDF remains in your Drive until you revoke access or delete it.',
  '',
  '## 📝 A complete Markdown notebook',
  '',
  '- Live Markdown preview and automatic saving',
  '- Code syntax highlighting and KaTeX math',
  '- Photos, file attachments, and drawings',
  '- Zoomable, drag-to-pan image viewer',
  '- Phonetic Assistance: IPA for English, hiragana for Japanese kanji, and pinyin for Chinese',
  '- Nested notebooks and multi-select organization',
  '- Pinning and newest-first sorting',
  '- Trash, restore, and permanent deletion',
  '- Search across notes, from the browser address bar, or within the current note',
  '- Created and updated timestamps',
  '- Import from Markdown, Markdown ZIP, JSON, Evernote ENEX, Word DOCX, or `.owl-note` packages',
  '- Export to Markdown ZIP, JSON, PDF, or `.owl-note` packages',
  '',
  '## 🦉 Ask Owl — retrieval and on-device AI',
  '',
  'Ask natural-language questions about your notes. Without on-device AI, Ask Owl displays matching excerpts. When the browser’s on-device `LanguageModel` API is available, it can generate grounded answers with citations.',
  '',
  '- Keyword retrieval across your notes',
  '- Optional meaning-based semantic search',
  '- One-click note summarization',
  '- Deterministic Markdown tidying without AI rewriting',
  '- On-device AI title suggestions',
  '- CJK-aware retrieval for Chinese, Japanese, and Korean text',
  '',
  'The optional semantic index requires a one-time model download of approximately 130 MB. Indexing and inference run locally.',
  '',
  'Try it now: open **🦉 Ask Owl** and click **Summarize** to summarize this note, or click **Tidy** to clean its Markdown without rewriting what it says.',
  '',
  '## 🔒 Private by design',
  '',
  '- No separate OWL-Note account',
  '- No subscription, OWL-Note backend, telemetry, or advertising',
  '- Notes stored in browser bookmarks when within sync limits',
  '- Capture, drawing, conversion, retrieval, and AI processing run locally',
  '- Content sent to Google Drive only when Drive sync or Drive sharing is explicitly enabled',
  '- Oversized content kept safely on the current device when Drive sync is off',
  '- Manifest V3 extension',
  '- Open source under GPL-3.0-or-later',
  '',
  'Optional Google Drive support can sync large notes and attachments. OWL-Note works with Chrome, Edge, and other Chromium-based browsers.',
  '',
  '---',
  '',
  'That is the tour. Delete this note whenever you like and start writing.',
  '',
].join('\n');
